# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tests.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 2, "", "tests.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0btests.proto\x12\x05tests"\xdb\x03\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x12\n\x05\x65mail\x18\x03 \x01(\tH\x01\x88\x01\x01\x12)\n\x06phones\x18\x04 \x03(\x0b\x32\x19.tests.Person.PhoneNumber\x12%\n\x04tags\x18\x05 \x03(\x0b\x32\x17.tests.Person.TagsEntry\x12\x16\n\x0coneof_string\x18\x06 \x01(\tH\x00\x12\x13\n\toneof_int\x18\x07 \x01(\x03H\x00\x12\x30\n\x0boneof_phone\x18\x08 \x01(\x0b\x32\x19.tests.Person.PhoneNumberH\x00\x1a\x44\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12%\n\x04type\x18\x02 \x01(\x0e\x32\x17.tests.Person.PhoneType\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"h\n\tPhoneType\x12\x1a\n\x16PHONE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11PHONE_TYPE_MOBILE\x10\x01\x12\x13\n\x0fPHONE_TYPE_HOME\x10\x02\x12\x13\n\x0fPHONE_TYPE_WORK\x10\x03\x42\x0b\n\tsomethingB\x08\n\x06_email",\n\x0b\x41\x64\x64ressBook\x12\x1d\n\x06people\x18\x01 \x03(\x0b\x32\r.tests.Personb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tests_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PERSON_TAGSENTRY"]._loaded_options = None
    _globals["_PERSON_TAGSENTRY"]._serialized_options = b"8\001"
    _globals["_PERSON"]._serialized_start = 23
    _globals["_PERSON"]._serialized_end = 498
    _globals["_PERSON_PHONENUMBER"]._serialized_start = 256
    _globals["_PERSON_PHONENUMBER"]._serialized_end = 324
    _globals["_PERSON_TAGSENTRY"]._serialized_start = 326
    _globals["_PERSON_TAGSENTRY"]._serialized_end = 369
    _globals["_PERSON_PHONETYPE"]._serialized_start = 371
    _globals["_PERSON_PHONETYPE"]._serialized_end = 475
    _globals["_ADDRESSBOOK"]._serialized_start = 500
    _globals["_ADDRESSBOOK"]._serialized_end = 544
# @@protoc_insertion_point(module_scope)
